# In reviews/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register viewsets with it.
router = DefaultRouter()
router.register(r'users', views.UserViewSet, basename='user')
router.register(r'movies', views.MovieViewSet, basename='movie')
router.register(r'reviews', views.ReviewViewSet, basename='review')
router.register(r'comments', views.CommentViewSet, basename='comment')

# The urlpatterns now simply include the URLs generated by the router.
# The `format_suffix_patterns` wrapper is not needed because the router
# handles format suffixes automatically.
urlpatterns = [
    path('', include(router.urls)),
]

# Do not include the following line. It is the cause of your error.
# urlpatterns = format_suffix_patterns(urlpatterns)
